init-repository: Check for cmake
And bail out with proper warning if cmake is missing

Change-Id: I39a9e340f873f8de05264d57b2a80fb754b30fbe
Reviewed-by:  Alexey Edelev <alexey.edelev@qt.io>

diff --git a/init-repository b/init-repository
--- a/init-repository
+++ b/init-repository
@@ -10,6 +10,12 @@ script_dir_path=`(cd "$script_dir_path"; /bin/pwd)`
 optfile=init-repository.opt
 opttmpfile=init-repository.opt.in
 
+# check whether cmake exists
+if ! [ -x "$(command -v cmake)" ]; then
+    echo "Error: cmake was not found. You need to install it before configuring Qt."
+    exit 1
+fi
+
 # Posix compatible way to truncate file
 : > "$optfile"
 : > "$opttmpfile"
